---
# handlers file for ansible-role-rh-demo-web-app
- name: restart gunicorn
  service:
    name: gunicorn
    state: restarted
    daemon_reload: true
    enabled: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
